== Deployment Strategy

Whenever a pull request is made on the GitHub repository, the Drone build server will go through a series of steps. It will first clone the repository and then use Semgrep to check for any irregularities in the code such as bugs or general bad code style. Next SonarQube will check the code against some of the same parameters and also check for any vulnerabilities. Then it attempts a build and finally it will run tests. Notably we have not implemented any tests, so this step always passes. It would of course have been beneficial to do testing and ideally we would have written tests to ensure that our code is working as intended. One way of doing this could have been to work test-driven so that we would have the test cases before even writing the functionality itself.

The results of the steps displayed above will be shown in the pull request and based on this output developers can then decide whether they wish to merge the incoming pull request or not manually.

If they decide that the pull request is okay to merge into the main branch the Drone server will initiate a second build and then deploy this build. It will create and push a Docker image to the DigitalOcean registry and then, using Snyk, scan for any vulnerabilities in the code. Then the live docker image created will be updated from the latest build and execute the https://github.com/Herover/itu-devops-h/blob/main/terraform/files/deploy.sh[deploy script]. Finally a release will be created in the GitHub repository.

