=== Work Process

==== Meetings

We had our meetings as a team every week in the exercise session since it was the best time for everyone to meet up. We mostly discussed what will be happening from then on, distributed the work of that week's exercises and evaluated finished development. Unfinished tasks and long-term tasks were briefly discussed to stay up to date on the ongoing development.

Work division for available tasks was overseen at the exercise sessions. While most work division was simple since there were multiple tasks, a few tasks were indivisible and forced a group member to focus on them for longer.

==== Work Division and Issue Tracking

For the ongoing tasks, online communication was done on Discord since it was much faster than meeting up and quick to evaluate actions. We had a specific channel for our pull requests where new ones were posted, allowing for quick reviews by sending notifications to everyone.

If any sort of issue happened that was not dependent on the current tasks, a message including the details was sent out so that it could be investigated.

We mostly had online meetings when such were required outside the exercise sessions, and we shared information either via Discord messages or GitHub issues. These meetings were held for knowledge sharing, major changes, or explaining hard-to-understand features.
