server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.110.0.4:3100/loki/api/v1/push

scrape_configs:
  - job_name: minitwit_scrape 
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [minitwit] 
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
    pipeline_stages:
      - regex:
          expression: '(method)=(?P<method>\w+)'
      - regex:
          expression: '(status)=(?P<status>\w+)'
      - regex:
          expression: '(?P<level>(INFO|WARN|ERROR|DEBUG|TRACE))'
      - labels:
          method:
          status:
          level:
