version: "3.3"

services:
  db:
    container_name: postgres-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: minitwituser
      POSTGRES_DB: minitwit
    volumes:
      - type: bind
        source: /mnt/minitwitdb/data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - link

networks:
  link:
