version: "3"

services:
  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /root/promtail/configs:/configs
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: -config.file=/configs/promtail-config.yaml
