kind: pipeline
type: digitalocean
name: Minitwit server

token:
  from_secret: token

server:
  image: ubuntu-20-04-x64
  size: c-2
  region: nyc1

steps:
- name: build
  commands:
  - chmod +x ./terraform/files/install_jdk_maven.sh
  - ./terraform/files/install_jdk_maven.sh
  - cd minitwit
  - chmod +x ./control.sh
  - ./control.sh build
  - ls -al
  when:
    event:
      include:
      - pull_request

- name: test
  commands:
  - echo Inser tests here...
  when:
    event:
      include:
      - pull_request

- name: deploy
  environment:
    DOCKER_USERNAME:
      from_secret: token
    DOCKER_PASSWORD:
      from_secret: token
  commands:
  - chmod +x ./terraform/files/install_docker.sh
  - ./terraform/files/install_docker.sh
  - cd minitwit
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.digitalocean.com
  - docker build --tag registry.digitalocean.com/minitwit/minitwit-server:latest --tag registry.digitalocean.com/minitwit/minitwit-server:$DRONE_BUILD_NUMBER .
  - docker push registry.digitalocean.com/minitwit/minitwit-server:latest
  - docker push registry.digitalocean.com/minitwit/minitwit-server:$DRONE_BUILD_NUMBER
  when:
    # TODO: Change so it happens on merge to main/prod/some live branch
    event:
    - promote
