---
kind: pipeline
type: docker
name: Minitwit server

steps:
- name: build
  image: maven:3.8.4-openjdk-17-slim
  commands:
  - cd minitwit
  - chmod +x ./control.sh
  - ./control.sh build
  - ls -al
  when:
    event:
      include:
      - pull_request

- name: test
  image: maven:3.8.4-openjdk-17-slim
  commands:
  - echo Inser tests here...
  when:
    event:
      include:
      - pull_request

- name: create and push docker image
  image: plugins/docker
  settings:
    registry: registry.digitalocean.com
    username:
      from_secret: token
    password:
      from_secret: token
    repo: registry.digitalocean.com/minitwit/minitwit-server
    tags:
      - "latest"
      - "${DRONE_BUILD_NUMBER}"
    dockerfile: minitwit/Dockerfile
    context: minitwit
  when:
    event:
    - promote

- name: snyk scan
  image: plugins/drone-snyk:1.0.1
  pull: if-not-exists
  privileged: true
  settings:
    snyk:
      from_secret: SNYK_TOKEN
    username:
      from_secret: token
    password:
      from_secret: token
    registry: registry.digitalocean.com
    image: registry.digitalocean.com/minitwit/minitwit-server:latest
    dockerfile: minitwit/Dockerfile
  when:
    event:
    - promote

- name: update live docker images
  image: alpine:3.15.0
  environment:
    DOCKER_USERNAME:
      from_secret: token
    DOCKER_PASSWORD:
      from_secret: token
    ROOT_PASSWORD:
      from_secret: root_password
    WEB_HOST:
      "143.198.249.10"
  commands:
  - apk add --no-cache sshpass openssh
  - sshpass -p "$ROOT_PASSWORD" scp -o StrictHostKeyChecking=no terraform/files/update_image.sh root@$WEB_HOST:/tmp/
  - sshpass -p "$ROOT_PASSWORD" ssh -o StrictHostKeyChecking=no root@$WEB_HOST chmod +x /tmp/update_image.sh
  - sshpass -p "$ROOT_PASSWORD" ssh -o StrictHostKeyChecking=no root@$WEB_HOST /tmp/update_image.sh registry.digitalocean.com/minitwit/minitwit-server $DRONE_BUILD_NUMBER $DOCKER_USERNAME $DOCKER_PASSWORD
  when:
    event:
    - promote

---

kind: signature
hmac: 174fea4f4cb1500f3ca02b3602223f82ee72168170b31625c015a4fadd100b8d