---
kind: pipeline
type: docker
name: Minitwit server pull request

trigger:
  event: [pull_request]

steps:
- name: build
  image: maven:3.8.4-openjdk-17-slim
  commands:
  - cd minitwit
  - chmod +x ./control.sh
  - ./control.sh build
  - ls -al

- name: test
  image: maven:3.8.4-openjdk-17-slim
  commands:
  - echo Inser tests here...

---

kind: pipeline
type: docker
name: Minitwit server deployment

trigger:
  branch:
  - main
  event:
  - push

steps:
- name: create and push docker image
  image: plugins/docker
  settings:
    registry: registry.digitalocean.com
    username:
      from_secret: token
    password:
      from_secret: token
    repo: registry.digitalocean.com/minitwit/minitwit-server
    tags:
      - "latest"
      - "${DRONE_BUILD_NUMBER}"
    dockerfile: minitwit/Dockerfile
    context: minitwit

- name: update live docker images
  image: alpine:3.15.0
  environment:
    DOCKER_USERNAME:
      from_secret: token
    DOCKER_PASSWORD:
      from_secret: token
    ROOT_PASSWORD:
      from_secret: root_password
    WEB_HOST:
      "143.198.249.10"
  commands:
  - apk add --no-cache sshpass openssh
  - sshpass -p "$ROOT_PASSWORD" scp -o StrictHostKeyChecking=no terraform/files/update_image.sh root@$WEB_HOST:/tmp/
  - sshpass -p "$ROOT_PASSWORD" ssh -o StrictHostKeyChecking=no root@$WEB_HOST chmod +x /tmp/update_image.sh
  - sshpass -p "$ROOT_PASSWORD" ssh -o StrictHostKeyChecking=no root@$WEB_HOST /tmp/update_image.sh registry.digitalocean.com/minitwit/minitwit-server $DRONE_BUILD_NUMBER $DOCKER_USERNAME $DOCKER_PASSWORD

- name: create github release
  image: alpine:3.15.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
  commands:
  # Install grep with support for P flag not available in bundled grep
  - apk add --no-cache git grep
  - wget https://github.com/cli/cli/releases/download/v2.6.0/gh_2.6.0_linux_amd64.tar.gz
  - tar xvfz gh_2.6.0_linux_amd64.tar.gz
  - cp gh_2.6.0_linux_amd64/bin/gh /usr/local/bin/gh
  # True is added so we can ignore env var warning
  - echo $GH_TOKEN | gh auth login --with-token || true
  # Assume first version tag is the one we want
  - version=$(grep -Po "(?<=\<version\>)[A-Z0-9\.\-]*" minitwit/pom.xml | head -n 1)
  - gh release create $version --generate-notes

---

kind: signature
hmac: 28f7b6f5a2cb99f8f4b02c4dea27e365ac60ca97a3707c590f9815477c87bf90