kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: ubuntu-20-04-x64
  size: s-1vcpu-1gb
  region: ams3

steps:
- name: testing
  commands:
  - chmod +x ./terraform/files/install_jdk_maven.sh
  - ./terraform/files/install_jdk_maven.sh
  - cd minitwit
  - chmod +x ./configure.sh
  - ./configure.sh build
  - ls -al
