version: '2'
services:
  drone-server:
    image: drone/drone:2.9.1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - drone
    volumes:
      - /opt/drone-data:/data
    environment:
      DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      DRONE_USER_FILTER: ${DRONE_USER_FILTER}
      DRONE_DATABASE_SECRET: ${DRONE_DATABASE_SECRET}
      DRONE_USER_CREATE: ${DRONE_USER_CREATE}
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://10.110.0.4:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                commit: commit
                event: event
                level: level
                msg: msg
                pipeline: pipeline
                ref: ref
                repo: repo
                time: time
                message: "[level, event, pipeline, msg, ref, commit, repo, time] | join(', ', @)"
          - labels:
              level:
              event:
              pipeline:
          - output:
              source: message
          - timestamp:
              source: time
              format: RFC3339

  drone-runner-docker:
    image: drone/drone-runner-docker:1
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_PROTO: ${DRONE_RPC_PROTO}
      DRONE_RPC_HOST: ${DRONE_RPC_HOST}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_UI_USERNAME: ${DRONE_UI_USERNAME}
      DRONE_UI_PASSWORD: ${DRONE_UI_PASSWORD}
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://10.110.0.4:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl)=(?P<level>\w+)'
          - regex:
              expression: '(time)=(?P<time>\w+)'
          - labels:
              level:
          - timestamp:
              source: time
              format: RFC3339

networks:
  drone:
    driver: bridge


